# Generated by Django 5.2.6 on 2025-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=30)),
                ("student_class", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
